FROM node:20-alpine as dev

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package*.json pnpm-lock.yaml tsconfig.json ./

ENV NODE_ENV=DEVELOPMENT

RUN pnpm install --frozen-lockfile

COPY ./ ./

RUN pnpm run prebuild
RUN pnpm run build
CMD [ "node", "dist/main.js" ]



