"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.postHello = exports.getHello = exports.number = exports.string = void 0;
/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
var fetcher_1 = require("@nestia/fetcher");
var typia_1 = __importDefault(require("typia"));
var NestiaSimulator_1 = require("./../utils/NestiaSimulator");
exports.string = __importStar(require("./string"));
exports.number = __importStar(require("./number"));
/**
 * @controller AppController.getHello()
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
function getHello(connection) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, !!connection.simulate
                    ? getHello.simulate(connection)
                    : fetcher_1.Fetcher.fetch(connection, getHello.ENCRYPTED, getHello.METHOD, getHello.path())];
        });
    });
}
exports.getHello = getHello;
(function (getHello) {
    var _this = this;
    getHello.METHOD = "GET";
    getHello.PATH = "/";
    getHello.ENCRYPTED = {
        request: false,
        response: false,
    };
    getHello.path = function () {
        return "/";
    };
    getHello.random = function (g) {
        return typia_1.default.random(g);
    };
    getHello.simulate = function (connection) { return __awaiter(_this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, getHello.random(typeof connection.simulate === 'object' &&
                    connection.simulate !== null
                    ? connection.simulate
                    : undefined)];
        });
    }); };
})(getHello || (exports.getHello = getHello = {}));
/**
 * @controller AppController.postHello()
 * @path POST /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
function postHello(connection, body) {
    var _a;
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_b) {
            return [2 /*return*/, !!connection.simulate
                    ? postHello.simulate(connection, body)
                    : fetcher_1.Fetcher.fetch(__assign(__assign({}, connection), { headers: __assign(__assign({}, ((_a = connection.headers) !== null && _a !== void 0 ? _a : {})), { "Content-Type": "application/json" }) }), postHello.ENCRYPTED, postHello.METHOD, postHello.path(), body)];
        });
    });
}
exports.postHello = postHello;
(function (postHello) {
    var _this = this;
    postHello.METHOD = "POST";
    postHello.PATH = "/";
    postHello.ENCRYPTED = {
        request: false,
        response: false,
    };
    postHello.path = function () {
        return "/";
    };
    postHello.random = function (g) {
        return typia_1.default.random(g);
    };
    postHello.simulate = function (connection, body) { return __awaiter(_this, void 0, void 0, function () {
        var assert;
        return __generator(this, function (_a) {
            assert = NestiaSimulator_1.NestiaSimulator.assert({
                method: postHello.METHOD,
                host: connection.host,
                path: postHello.path()
            });
            assert.body(function () { return typia_1.default.assert(body); });
            return [2 /*return*/, postHello.random(typeof connection.simulate === 'object' &&
                    connection.simulate !== null
                    ? connection.simulate
                    : undefined)];
        });
    }); };
})(postHello || (exports.postHello = postHello = {}));
