export const JWT_OPTIONS = 'JWT_OPTIONS';

export const ER_JWT_AUTH_ACCESS_GUARD = 'ER_JWT_AUTH_ACCESS_GUARD';
export const ER_JWT_AUTH_REFRESH_GUARD = 'ER_JWT_AUTH_REFRESH_GUARD';
export const EMS_JWT_AUTH_ACCESS_GUARD = 'EMS_JWT_AUTH_ACCESS_GUARD';
export const EMS_JWT_AUTH_REFRESH_GUARD = 'EMS_JWT_AUTH_REFRESH_GUARD';
